### ISSUE TITLE
Avoid using SDKs or clients in the module implementation: use it only in the tests/examples

### ISSUE THREAD

**Issue by mdelapenya** [Mariscal6/testcontainers-spicedb-go#3]
We try to avoid that to not couple the module to any SDK so users can choose whatever they need/want. Please take a look at https://github.com/Mariscal6/testcontainers-spicedb-go/blob/bc376875f7f8812e82e5cde89b88172aed541076/spicedb.go#L136-L145

If possible, I'd go with contributing a wait strategy in that customisation

**Comment by Mariscal6** [comment]
Hi @mdelapenya! Sorry for the delay in the response. The aim was to facilitate db creation. What do you propose to change this without renouncing to this functionality? Maybe defining a new field in the structure as a function, and let them define how the migration is executed?
